# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "about"
name = "About"
url = "/about"
[main.params]
icon = "about"
newtab = false

#[[social]]
#identifier = "github"
#name = "GitHub"
#url = "https://github.com/CaiJimmy/hugo-theme-stack"

#[social.params]
#icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/bromander_simon"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/simonbromander"

[social.params]
icon = "linkedin"
